#!/bin/sh
# install.sh — download and install the zulip-acp binary.
#
# GENERATED by github.com/kfet/distkit/installsh. Do not edit by hand:
# `make install.sh` regenerates it, and the drift check in CI fails when this
# file differs from what the template would produce.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kfet/zulip-acp/main/install.sh | sh
#   curl -fsSL https://raw.githubusercontent.com/kfet/zulip-acp/main/install.sh | VERSION=v0.21.0 sh
#   curl -fsSL https://raw.githubusercontent.com/kfet/zulip-acp/main/install.sh | BIN_DIR=$HOME/bin sh
#
# Environment overrides:
#   VERSION       release tag to install (default: latest)
#   BIN_DIR       install destination (default: /usr/local/bin, or $HOME/.local/bin when that is not writable)
#   PREFIX        legacy alias: BIN_DIR becomes $PREFIX/bin
#   REPO          github owner/repo (default: kfet/zulip-acp)
#   OS            override detected OS (linux | darwin)
#   ARCH          override detected arch (amd64 | arm64 | armv6)
#   GITHUB_TOKEN  token for a private repo, or to dodge API rate limits
#   GITHUB_API    API root override (GitHub Enterprise, or a test double)
#   GITHUB_HOST   release-download host override; default https://github.com
#
# Requires: curl or wget, uname, mktemp, and one of sha256sum/shasum.
#
# On macOS prefer `brew install kfet/ai/zulip-acp` — it upgrades with the rest
# of your system. This script is for Linux hosts (Raspberry Pi included).

set -eu

REPO="${REPO:-kfet/zulip-acp}"
BIN_NAME="zulip-acp"
VERSION="${VERSION:-latest}"

log()  { printf '==> %s\n' "$*" >&2; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# ---- fetch helper ---------------------------------------------------------
# curl is preferred but a minimal Debian image ships wget and not curl, so
# both are supported. Neither is asked to follow the browser download URL:
# everything goes through api.github.com, which works for a private repo once
# GITHUB_TOKEN is set and is identical for a public one.
download() {
	# download URL OUTFILE [ACCEPT]
	# The auth header is passed as a whole argument in each branch rather
	# than spliced in with ${VAR:+…}: an unquoted parameter expansion would
	# word-split "Authorization: Bearer x" into three arguments and send a
	# malformed header.
	_accept="${3:-application/vnd.github+json}"
	if have curl; then
		if [ -n "${GITHUB_TOKEN:-}" ]; then
			curl -fsSL --retry 3 -H "Accept: $_accept" \
				-H "Authorization: Bearer $GITHUB_TOKEN" -o "$2" "$1"
		else
			curl -fsSL --retry 3 -H "Accept: $_accept" -o "$2" "$1"
		fi
	elif have wget; then
		if [ -n "${GITHUB_TOKEN:-}" ]; then
			wget -q --header="Accept: $_accept" \
				--header="Authorization: Bearer $GITHUB_TOKEN" -O "$2" "$1"
		else
			wget -q --header="Accept: $_accept" -O "$2" "$1"
		fi
	else
		die "need curl or wget"
	fi
}

# ---- detect platform ------------------------------------------------------
detect_os() {
	case "$(uname -s)" in
		Linux) echo linux ;;
		Darwin) echo darwin ;;
		*) die "unsupported OS: $(uname -s)" ;;
	esac
}

detect_arch() {
	case "$(uname -m)" in
		x86_64|amd64)  echo amd64 ;;
		arm64|aarch64) echo arm64 ;;
		# 32-bit ARM userland: a Pi Zero reports armv6l, 32-bit Raspberry Pi
		# OS on newer boards armv7l or armv8l. One asset covers all three —
		# it is built at GOARM=6, the only variant every one of them can
		# execute.
		armv6l|armv7l|armv8l|armv6|armv7)
			# $OS is already resolved here and honours the operator's
			# override; re-deriving it from uname would refuse a platform
			# the operator explicitly named.
			[ "$OS" = linux ] || die "unsupported arch: $(uname -m) on $OS"
			echo armv6 ;;
		*) die "unsupported arch: $(uname -m) (releases cover amd64 | arm64 | armv6)" ;;
	esac
}

OS="${OS:-$(detect_os)}"
ARCH="${ARCH:-$(detect_arch)}"

# ---- resolve version ------------------------------------------------------
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

api="${GITHUB_API:-https://api.github.com}/repos/$REPO/releases"
# The download is run as an `if` condition on purpose: `set -e` would
# otherwise abort here with curl's bare "error: 22", and the two things that
# actually go wrong at this step — a private repo with no token, and GitHub's
# per-IP unauthenticated rate limit spent by a whole NAT'd fleet — both look
# like an unexplained HTTP failure unless we say so.
api_hint="a private repo needs GITHUB_TOKEN; so does a spent unauthenticated API rate limit (GitHub counts it per IP address, so a shared network exhausts it)"
if [ "$VERSION" = latest ]; then
	log "resolving latest release for $REPO"
	download "$api/latest" "$tmpdir/release.json" || die "cannot read the latest release of $REPO: $api_hint"
else
	download "$api/tags/$VERSION" "$tmpdir/release.json" || die "cannot read release $VERSION of $REPO: $api_hint"
fi
# Extract "tag_name": "v…" without jq, which is not installable from here.
VERSION="$(sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$tmpdir/release.json" | head -n1)"
[ -n "$VERSION" ] || die "no tag_name in the release JSON from $REPO: $api_hint"
VERSION_NO_V="${VERSION#v}"
log "installing $REPO $VERSION ($OS/$ARCH)"

ASSET="zulip-acp-${OS}-${ARCH}"
BASE_URL="${GITHUB_HOST:-https://github.com}/$REPO/releases/download/$VERSION"

# With no token, the plain releases/download URL is used: one redirect, no
# JSON parsing. With a token the API asset URL is required instead, because
# the download host 404s a private repo no matter what you send it.
#
# Finding that URL means picking one object out of the assets array in POSIX
# sh: strip all whitespace, break the array into one object per line, then
# match the exact "name":"…" pair. The closing quote in the pattern is what
# stops "foo-linux-arm" from matching "foo-linux-arm64".
fetch_asset() {
	# fetch_asset NAME OUTFILE
	if [ -n "${GITHUB_TOKEN:-}" ]; then
		_url="$(tr -d ' \t\n' < "$tmpdir/release.json" \
			| sed 's/},{/}\
{/g' \
			| grep -F "\"name\":\"$1\"" \
			| sed -n 's/.*"url":"\([^"]*releases\/assets\/[0-9]*\)".*/\1/p' \
			| head -n1)"
		[ -n "$_url" ] || die "release $VERSION has no asset $1"
		download "$_url" "$2" application/octet-stream || die "cannot download $1 from $REPO: $api_hint"
	else
		download "$BASE_URL/$1" "$2" application/octet-stream \
			|| die "cannot download $1 from $REPO $VERSION (no such asset for this platform, or the release is not public): $api_hint"
	fi
}

log "downloading $ASSET"
fetch_asset "$ASSET" "$tmpdir/$ASSET"

# ---- verify checksum ------------------------------------------------------
fetch_asset "checksums.txt" "$tmpdir/checksums.txt"
if have sha256sum; then SHA="sha256sum"
elif have shasum;   then SHA="shasum -a 256"
else die "need sha256sum or shasum on PATH"
fi
expected="$(awk -v f="$ASSET" '$2==f || $2=="*" f {print $1; exit}' "$tmpdir/checksums.txt")"
[ -n "$expected" ] || die "no checksum entry for $ASSET in checksums.txt"
actual="$(cd "$tmpdir" && $SHA "$ASSET" | awk '{print $1}')"
[ "$expected" = "$actual" ] || die "checksum mismatch for $ASSET (expected $expected, got $actual)"
log "checksum ok"

src="$tmpdir/$ASSET"
chmod +x "$src"

# ---- install --------------------------------------------------------------
# PREFIX is the older spelling used by some of these scripts; honour it so an
# existing runbook keeps working, but BIN_DIR wins when both are set.
if [ -z "${BIN_DIR:-}" ] && [ -n "${PREFIX:-}" ]; then
	BIN_DIR="$PREFIX/bin"
fi
if [ -z "${BIN_DIR:-}" ]; then
	if [ -w /usr/local/bin ] 2>/dev/null || [ "$(id -u)" = 0 ]; then
		BIN_DIR=/usr/local/bin
	else
		BIN_DIR="$HOME/.local/bin"
	fi
fi
mkdir -p "$BIN_DIR"
dest="$BIN_DIR/$BIN_NAME"

# Install to a sibling and rename: a running copy of this binary cannot be
# written in place (ETXTBSY), but its directory entry can be replaced, and the
# rename is atomic so no one ever sees a half-written file.
stage="$BIN_DIR/.$BIN_NAME.new.$$"
if [ -w "$BIN_DIR" ]; then
	cp "$src" "$stage" && chmod 0755 "$stage" && mv -f "$stage" "$dest"
elif have sudo; then
	log "installing to $dest via sudo"
	sudo cp "$src" "$stage" && sudo chmod 0755 "$stage" && sudo mv -f "$stage" "$dest"
else
	die "cannot write to $BIN_DIR (set BIN_DIR=… to override)"
fi

log "installed $dest"
case ":$PATH:" in
	*":$BIN_DIR:"*) ;;
	*) warn "$BIN_DIR is not on \$PATH. add it to your shell rc:
         export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

"$dest" --version 2>/dev/null || true

printf '\nnext:\n'
printf '  %s\n' 'zulip-acp --print-paths                      # resolved config, state dir and agent command'
printf '  %s\n' 'install ~/.config/zulip-acp/config.json      # see docs/config.example.json'
printf '  %s\n' 'install ~/.config/zulip-acp/env  (mode 0600) # ZULIP_API_KEY=...'
printf '  %s\n' 'systemctl --user enable --now zulip-acp      # packaging/systemd/zulip-acp.service'
printf '  %s\n' 'upgrades are zulip-acp update, never a hand-placed binary'
